name: Build Periodic Backup plugin

on: [push, pull_request]

jobs:
  build:
    name: Build on JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [ '8', '11' ]
    runs-on: ubuntu-latest

    steps:
      - name: Sync Repository
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PeriodicBackup-Modified-${{ matrix.jdk }}.hpi
          path: target/*.hpi